### PR TITLE
pkp/pkp-lib#10101 Fix fatal error when removing a journal due to fore…

### LINKED ISSUE #10101: Fatal error when removing a journal
**Describe the bug**
The error was simulated on the `main` branch, but it probably also exists on `stable-3_4_0`.

```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ojs35`.`review_assignments`, CONSTRAINT `review_assignments_submission_id_foreign` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`submission_id`)) in lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:605
Stack trace:
#0 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illuminate\Database\{closure}('DELETE FROM jou...', Array)
#2 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback('DELETE FROM jou...', Array, Object(Closure))
#3 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\Database\Connection->run('DELETE FROM jou...', Array, Object(Closure))
#4 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\Connection->affectingStatement('DELETE FROM jou...', Array)
#5 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 lib/pkp/classes/db/DAO.php(174): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 lib/pkp/classes/db/SchemaDAO.php(213): PKP\db\DAO->update('DELETE FROM jou...', Array)
#8 lib/pkp/classes/db/SchemaDAO.php(203): PKP\db\SchemaDAO->deleteById(1)
#9 lib/pkp/classes/services/PKPContextService.php(664): PKP\db\SchemaDAO->deleteObject(Object(APP\journal\Journal))
#10 lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(289): PKP\services\PKPContextService->delete(Object(APP\journal\Journal))
#11 [internal function]: PKP\controllers\grid\admin\context\ContextGridHandler->deleteContext(Array, Object(APP\core\Request))
#12 lib/pkp/classes/core/PKPRouter.php(328): call_user_func(Array, Array, Object(APP\core\Request))
#13 lib/pkp/classes/core/PKPComponentRouter.php(273): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#14 lib/pkp/classes/core/Dispatcher.php(161): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#15 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#16 index.php(21): PKP\core\PKPApplication->execute()
#17 {main}
```

**To Reproduce**
1. Load a dataset from the datasets repository
2. Attempt to delete the publicknowledge journal

**What application are you using?**
OJS /main

### PR DESCRIPTION
**Pull request by Hafsa-Naeem**
Fixes #10101

### CODE REVIEW

File: classes/submission/reviewAssignment/Repository.php [hunk 1]
```diff
@@ -227,6 +227,39 @@ public function deleteMany(Collector $collector)
...
+        $reviewAssignmentCollector = $this->getCollector();
+        $reviewAssignmentCollector->filterByContextIds([$contextId]);
+        $reviewAssignments = $reviewAssignmentCollector->getMany();
+    
+        foreach ($reviewAssignments as $reviewAssignment) {
+            $this->delete($reviewAssignment);
+        }
+    
+        // delete review rounds associated with this context
+        $this->deleteReviewRoundsByContextId($contextId);
```
Comment (asmecher) [inline classes/submission/reviewAssignment/Repository.php:248]: Best to just move the `getDAO` / `deleteByContextId` calls directly here, rather than creating a new function.

File: classes/submission/reviewAssignment/Repository.php [hunk 2]
```diff
@@ -227,6 +227,39 @@ public function deleteMany(Collector $collector)
...
+     *
+     * @param int $contextId
+     * @return void
+     */
+    public function deleteByContextId($contextId)
+    {
+        // using reviewAssignmentCollector to fetch and delete all review assignments for the context
+        $reviewAssignmentCollector = $this->getCollector();
+        $reviewAssignmentCollector->filterByContextIds([$contextId]);
+        $reviewAssignments = $reviewAssignmentCollector->getMany();
```
Comment (asmecher) [inline classes/submission/reviewAssignment/Repository.php:241]: You can use `getIds` instead of `getMany`, then just iterate through the IDs. That'll use significantly less memory and resources than `getMany`, which will instantiate each object.

File: classes/submission/reviewAssignment/Repository.php [hunk 3]
```diff
@@ -227,6 +227,28 @@ public function deleteMany(Collector $collector)
...
+     */
+    public function deleteByContextId(int $contextId): void
+    {
+        // using reviewAssignmentCollector to fetch ids of all review assignments for the context
+        $reviewAssignmentCollector = $this->getCollector();
+        $reviewAssignmentCollector->filterByContextIds([$contextId]);
+        $reviewAssignmentIds = $reviewAssignmentCollector->getIds();
+    
+        foreach ($reviewAssignmentIds as $reviewAssignmentId) {
+            $reviewAssignment = $this->get($reviewAssignmentId);
```
Comment (asmecher) [inline classes/submission/reviewAssignment/Repository.php:241]: You should be able to use `$this->dao->deleteById($reviewAssignmentId)` rather than needing to fetch/instantiate the object.

Comment (Hafsa-Naeem) [reply classes/submission/reviewAssignment/Repository.php:241]: @asmecher Thank you for comment regarding the use of `$this->dao->deleteById($reviewAssignmentId)`. But I noticed that our current `DAO.php` doesn't have this method implemented yet. Would you prefer I go ahead and add it?

Comment (asmecher) [reply classes/submission/reviewAssignment/Repository.php:241]: Have a look at the parent class: https://github.com/pkp/pkp-lib/blob/3a92240297339f296ae561c7e3b291b156957eb8/classes/db/SchemaDAO.php#L211
