### PR TITLE
pkp/pkp-lib#10157 Moved issueIds out of publication_settings

### LINKED ISSUE #10157: Move publication to issue_id relationship out of publication_settings table
**Describe the bug**
Raised in https://github.com/pkp/pkp-lib/discussions/7975 and elsewhere:

Storing the issue ID for the publication in the `publication_settings` table is problematic for several reasons:
- It doesn't support relational integrity
- It performs poorly due to `setting_value` essentially being a blob column

For these reasons, the issue ID should instead be stored as an `issue_id` column in `publications`.

Note that this column will apply to OJS only, as OMP and OPS don't have issue-based publication!

### PR DESCRIPTION
**Pull request by Hafsa-Naeem**
fix #10157

### CODE REVIEW

File: classes/publication/Collector.php [hunk 1]
```diff
@@ -79,6 +81,17 @@ public function filterBySubmissionIds(?array $submissionIds): self
         return $this;
     }
 
+    /**
+     * Set the filter for issue IDs to limit the publications retrieved.
+     *
+     * @param array|null $issueIds An array of issue IDs to filter by, or null to remove the filter.
```
Comment (jonasraoni) [inline classes/publication/Collector.php:87]: When possible, I think the shorter syntax is preferred:

```suggestion
     * @param ?int[] $issueIds An array of issue IDs to filter by, or null to remove the filter.
```

File: classes/galley/DAO.php [hunk 2]
```diff
@@ -276,7 +275,8 @@ public function getExportable(int $contextId, $pubIdType = null, $title = null,
             ->when($pubIdType != null, fn (Builder $q) => $q->where('gs.setting_name', '=', "pub-id::{$pubIdType}")->whereNotNull('gs.setting_value'))
             ->when($title != null, fn (Builder $q) => $q->where('pst.setting_name', '=', 'title')->where('pst.setting_value', 'LIKE', "%{$title}%"))
             ->when($author != null, fn (Builder $q) => $q->whereRaw("CONCAT(COALESCE(asgs.setting_value, ''), ' ', COALESCE(asfs.setting_value, '')) LIKE ?", ["%{$author}%"]))
-            ->when($issueId != null, fn (Builder $q) => $q->where('ps.setting_name', '=', 'issueId')->where('ps.setting_value', '=', $issueId)->where('ps.locale', '=', ''))
+            ->when($issueId != null, fn (Builder $q) => $q->where('p.issue_id', '=', $issueId))
```
Comment (jonasraoni) [inline classes/galley/DAO.php:278]:
```suggestion
            ->when($issueId !== null, fn (Builder $q) => $q->where('p.issue_id', '=', $issueId))
```

**Comment by asmecher** [comment]
@Hafsa-Naeem, the `issue_id` / `publication_id` relationship is only applicable to OJS, but we're adding it here to `pkp-lib` which will also affect OMP and OPS. Could you see if you can isolate the changes to OJS only? The best case would be for `issue_id` code only to appear in the OJS repo, but if it is necessary for some of those concerns to move into pkp-lib, then it would need to be an optional relationship.

**Review by asmecher — CHANGES_REQUESTED** [review]
https://github.com/pkp/pkp-lib/pull/10298#issuecomment-2313405065
