### PR TITLE
pkp/pkp-lib#10101 Fix fatal error when removing a journal due to fore…

### LINKED ISSUE #10101: Fatal error when removing a journal
**Describe the bug**
The error was simulated on the `main` branch, but it probably also exists on `stable-3_4_0`.

```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ojs35`.`review_assignments`, CONSTRAINT `review_assignments_submission_id_foreign` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`submission_id`)) in lib\pkp\lib\vendor\laravel\framework\src\Illuminate\Database\Connection.php:605
Stack trace:
#0 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(605): PDOStatement->execute()
#1 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illuminate\Database\{closure}('DELETE FROM jou...', Array)
#2 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback('DELETE FROM jou...', Array, Object(Closure))
#3 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\Database\Connection->run('DELETE FROM jou...', Array, Object(Closure))
#4 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\Connection->affectingStatement('DELETE FROM jou...', Array)
#5 lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\Database\DatabaseManager->__call('affectingStatem...', Array)
#6 lib/pkp/classes/db/DAO.php(174): Illuminate\Support\Facades\Facade::__callStatic('affectingStatem...', Array)
#7 lib/pkp/classes/db/SchemaDAO.php(213): PKP\db\DAO->update('DELETE FROM jou...', Array)
#8 lib/pkp/classes/db/SchemaDAO.php(203): PKP\db\SchemaDAO->deleteById(1)
#9 lib/pkp/classes/services/PKPContextService.php(664): PKP\db\SchemaDAO->deleteObject(Object(APP\journal\Journal))
#10 lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(289): PKP\services\PKPContextService->delete(Object(APP\journal\Journal))
#11 [internal function]: PKP\controllers\grid\admin\context\ContextGridHandler->deleteContext(Array, Object(APP\core\Request))
#12 lib/pkp/classes/core/PKPRouter.php(328): call_user_func(Array, Array, Object(APP\core\Request))
#13 lib/pkp/classes/core/PKPComponentRouter.php(273): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#14 lib/pkp/classes/core/Dispatcher.php(161): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#15 lib/pkp/classes/core/PKPApplication.php(379): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#16 index.php(21): PKP\core\PKPApplication->execute()
#17 {main}
```

**To Reproduce**
1. Load a dataset from the datasets repository
2. Attempt to delete the publicknowledge journal

**What application are you using?**
OJS /main

### PR DESCRIPTION
**Pull request by Hafsa-Naeem**
Fixes #10101

### CODE REVIEW

File: classes/submission/reviewAssignment/ReviewAssignmentDAO.php [hunk 1]
```diff
@@ -669,6 +669,41 @@ public function deleteByReviewRoundId($reviewRoundId): int
...
+        }
+    }
+    
+    /**
+     * Delete all review rounds for a given submission ID.
+     *
+     * @param int $submissionId
+     * @return void
+     */
+    public function deleteReviewRoundsBySubmissionId($submissionId)
```
Comment (asmecher) [inline classes/submission/reviewAssignment/ReviewAssignmentDAO.php:700]: There already is a `ReviewRoundDAO::deleteBySubmissionId` you can use for this.

File: classes/submission/reviewAssignment/ReviewAssignmentDAO.php [hunk 2]
```diff
@@ -669,6 +669,41 @@ public function deleteByReviewRoundId($reviewRoundId): int
...
             ->count();
     }
+
+    /**
+     * Delete all review assignments and review rounds for a given context ID.
+     *
+     * @param int $contextId
+     * @return void
+     */
+    public function deleteByContextId($contextId)
```
Comment (asmecher) [inline classes/submission/reviewAssignment/ReviewAssignmentDAO.php:679]: For new code in `main`, use explicit typehinting:
```php
public function deleteByContextId(int $contextId) : void
```
And remove the redundant info from the self-documentation, which would then read just:
```
    /**
     * Delete all review assignments and review rounds for a given context ID.
     */
```

File: classes/submission/reviewAssignment/ReviewAssignmentDAO.php [hunk 3]
```diff
@@ -669,6 +669,41 @@ public function deleteByReviewRoundId($reviewRoundId): int
...
+    {
+        // retrieve all submission IDs for the context
+        $submissionIds = DB::table('submissions')
```
Comment (asmecher) [inline classes/submission/reviewAssignment/ReviewAssignmentDAO.php:682]: There are two ways of going about this:

1. By getting a list of submission IDs, then iterating through them and deleting content one by one. (This is the approach you've taken.)
    - Rather than getting the list of submission IDs directly here, it would be better to rely on the submission code to do this:
        ```php
        $submissionIds = Repo::submission()->getCollector()->filterByContextIds([$contextId])->getIds();
        ```
    - Likewise, as I've mentioned below, it's better to delegate the review round deletion to the DAO responsible for that entity.
2. This would run faster, as it doesn't require iteration, but is riskier: code the deletion without iteration.
    ```php
    DB::table('review_assignments AS ra')->join('submissions AS s', 'ra.submission_id', '=', 's.submission_id')->where('s.context_id', $contextId)->delete();
    ```

I'm not 100% confident which approach is best in this case. The first approach will be slow, because a context might have a lot of submissions. But it's a rarely used operation, so performance isn't important. Optimizing the deletions to avoid iteration will be quick, but will not behave well with things like hook callbacks etc.
